const PDFDocument = require("pdfkit");
const fs = require("fs");

const generateMedicalHistoryPDF = (medicalHistory, outputPath) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });

      // Pipe the PDF to a file
      const stream = fs.createWriteStream(outputPath);
      doc.pipe(stream);

      // Add a header
      doc
        .fontSize(24)
        .font("Helvetica-Bold")
        .text("Patient Medical History", { align: "center" })
        .moveDown(1);

      // Add patient details section
      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("Patient Details", { underline: true })
        .moveDown(0.5);

      doc
        .fontSize(12)
        .font("Helvetica")
        .text(`Government ID: ${medicalHistory.gov_id}`)
        .text(`Notes: ${medicalHistory.notes || "N/A"}`)
        .moveDown(1);

      // Add medical history details section
      doc
        .fontSize(16)
        .font("Helvetica-Bold")
        .text("Medical History Details", { underline: true })
        .moveDown(0.5);

      const details = [
        { label: "Loss of Vision", value: medicalHistory.loss_of_vision || "N/A" },
        { label: "Redness", value: medicalHistory.redness || "N/A" },
        { label: "Watering", value: medicalHistory.watering || "N/A" },
        { label: "Discharge Type", value: medicalHistory.discharge_type || "N/A" },
        { label: "Itching", value: medicalHistory.itching || "N/A" },
        { label: "Pain", value: medicalHistory.pain_final || "N/A" },
        { label: "Hypertension (HTN)", value: medicalHistory.htn || "N/A" },
        { label: "Diabetes Mellitus (DM)", value: medicalHistory.dm || "N/A" },
        { label: "Heart Disease", value: medicalHistory.heart_disease || "N/A" },
        { label: "Allergy Drops", value: medicalHistory.allergy_drops || "N/A" },
        { label: "Contact Lenses Use", value: medicalHistory.contact_lenses_use || "N/A" },
        { label: "Cataract or Injury", value: medicalHistory.cataract_or_injury || "N/A" },
        { label: "Retinal Lasers", value: medicalHistory.retinal_lasers || "N/A" },
      ];

      details.forEach((item) => {
        doc
          .fontSize(12)
          .font("Helvetica")
          .text(`${item.label}:`, { continued: true })
          .font("Helvetica-Bold")
          .text(` ${item.value}`);
      });

      doc.moveDown(1);

      // Add a footer
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(
          "Generated by ExamCare Health Management System",
          50,
          doc.page.height - 50,
          { align: "center" }
        );

      // Finalize the PDF
      doc.end();

      // Resolve the promise when the stream finishes
      stream.on("finish", () => resolve(outputPath));
      stream.on("error", reject);
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateMedicalHistoryPDF };